#--------------------------------------------------------------------------------
# Macro file to control the general simulation settings, world size and material, 
# and different detectors size, placement, data to record, etc.

#--------------------------------------------------------------------------------
# World
# World dimensions must be big enough to contain everything else inside
/world/halfdimensions 25. 020. 050. mm		
/world/material G4_Galactic #Vacuum

#--------------------------------------------------------------------------------
# Detectors

# - Absorption
/detector/absorption/halfdimensions 00.001 10.112 06.004 mm
/detector/absorption/xpixels 512#2560
/detector/absorption/ypixels 304#1520

# - Fluorescence
/detector/fluorescence/halfdimensions 02.00 00.01 01.00 cm
/detector/fluorescence/fullmapping False
/detector/fluorescence/fullfield   False
/detector/fluorescence/bins        2000
/detector/fluorescence/maxenergy     50. keV

#--------------------------------------------------------------------------------


