#--------------------------------------------------------------------------------
# Macro file to control the general simulation settings, world size and material, 
# and different detectors size, placement, data to record, etc.

#--------------------------------------------------------------------------------
# General

/simulation/seed 0
/simulation/graphics false
/world/visualization false	

#--------------------------------------------------------------------------------
# World

/world/size 4400 100 100 mm		
/world/material G4_Galactic

#--------------------------------------------------------------------------------
# Detectors

# - Absorption
/detector/absorption/halfdimensions 00.001 10.0112 6.004 mm
/detector/absorption/xpixels 434
/detector/absorption/ypixels 302

# - Fluorescence
/detector/fluorescence/halfdimensions 2 0.01 1 cm
/detector/fluorescence/bins 1000
/detector/fluorescence/maxenergy 20 keV
/detector/fluorescence/fullmapping true
/detector/fluorescence/fullfield true

# - Beam
/beam/bins 2000
/beam/maxenergy 175 keV

#--------------------------------------------------------------------------------
