# macrofile to control the physics of the simulation

/physics/gamma/livermore/photoelectric True
/physics/gamma/livermore/comptomscattering True
/physics/gamma/livermore/rayleighscattering True
/physics/gamma/fluorescence False
/physics/gamma/refraction False

# Make sure to change particle to opticalphoton if True in /beam/particle
/physics/opticalphoton/refraction False
/physics/opticalphoton/absorption False


