#--------------------------------------------------------------
# Macro file to place the samples in the world from sampleGeometry.mac
# 
# Place the objects

/sample/G4LogicalVolume/material   ObjectA AlSi10Mg
/sample/G4LogicalVolume/colour     ObjectA blue
/sample/G4VPhysicalVolume/position ObjectA 00.00 00.00 -1.10 mm
/sample/G4VPhysicalVolume/rotation ObjectA 00.00 00.00 00.00 deg

/sample/G4LogicalVolume/material ObjectB IN625
/sample/G4LogicalVolume/colour ObjectB red
/sample/G4VPhysicalVolume/position ObjectB 00.00 00.00 03.60 mm
/sample/G4VPhysicalVolume/rotation ObjectB 00.00 00.00 02.00 deg

/sample/checkforalloverlaps true
/sample/rotation/radius     00.00 mm			
/sample/tilt/anglex         10.00 deg
/sample/tilt/angley         00.00 deg
/sample/tilt/centre         00.00 00.00 00.00 mm

#ObjectA z -0.11cm
#ObjectB z +0.36cm

