package:
        name: geant4tomosim
        version: "1.0.0"

source:
        git_url: https://github.com/OliWenman/geant4tomosim.git
        git_rev: 1bd54c73a7fa951acbf9530c74ddb2b0ef646636

build:
        number: 0
        
requirements:
        build:
                - cmake
                - {{ compiler('cxx') }}
        host:
                - geant4
                - python
                - cython
                - xraylib
        run:
                - python
                - geant4
                - xraylib
                - h5py
                - numpy
                - matplotlib

test:
        import:
                - sim


        
