package:
        name: geant4tomosim
        version: "1.0.0"

source:
        path: ..

build:
        number: 0
        
requirements:
        build:
                - cmake
                - {{ compiler('cxx') }}
                - pkg-config
        host:
                - geant4
                - python
                - cython
                - xraylib
                - numpy
        run:
                - python
                - geant4
                - xraylib
                - h5py
                - numpy
                - matplotlib

test:
        imports:
                - sim


        
