#SETTINGS TO CONTROL SIMULATION

#--------------------------------------------------------------
# GENERAL

#/simulation/verbose 0
#/simulation/seed 0

#--------------------------------------------------------------
# PHYSICS

/physics/addPhysics/EM LivermorePhysics		
/physics/EM/PhotoElectricEffect true
/physics/EM/ComptonScattering false
/physics/EM/RayleighScattering false
/physics/EM/Fluorescence false
/physics/EM/Refraction true
/Physics/Gamma/Absorption false

#--------------------------------------------------------------
# DATA

/data/Seed 0 
/data/verbose 1
/data/bins 2000
/data/fluorescence/fullmapping false
/data/fluorescence/fullfield false

#--------------------------------------------------------------
# WORLD

/world/size 1000 3.2 2.1 cm		
/world/material G4_Galactic
/world/visualization false	

#--------------------------------------------------------------
# DETECTORS

/detector/absorption/rows 250
/detector/absorption/columns 210
/detector/absorption/halfdimensions 0.1 1.25 1.05 cm
/detector/fluorescence/halfdimensions 2 0.01 1 cm

#--------------------------------------------------------------
# BEAM

/beam/particle gamma
/beam/position/halfx 1.05 cm
/beam/position/halfy 1.25 cm
/beam/MaxEnergy 30 keV

#--------------------------------------------------------------
# OTHER

/Target/CheckAllOverlaps false
/Target/OffSet/Radius 0.0 mm			
/Target/OffSet/Centre 0.0 0.0 0.0 mm
